=== joeyramone76/appvet/appvet2.0_installer_bin/deploy/appvet_files/conf/tool_adapters/ToolServiceAdapter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://csrc.nist.gov/projects/appvet"
	xmlns:appvet="http://csrc.nist.gov/projects/appvet" elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!-- $$Id: ToolServiceAdapter.xsd 38580 2014-04-03 19:53:51Z steveq $$ -->

	<element name="ToolServiceAdapter">
        <annotation>
        	<documentation>The ToolServiceAdapter defines properties for an AppVet tool service.</documentation>
        </annotation>
        <complexType>
			<sequence>
				<element name="Description" type="appvet:DescriptionType"
					maxOccurs="1" minOccurs="1" >
					<annotation>
						<documentation>The Description element defines general information about an AppVet tool service.</documentation>
					</annotation></element>
				<element name="Protocol" type="appvet:ProtocolType"
					maxOccurs="1" minOccurs="1" >
					<annotation>
						<documentation>The Protocol element defines protocol information for an AppVet tool service.</documentation>
					</annotation></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="DescriptionType">
		<sequence>
			<element name="Name" type="string" maxOccurs="1" minOccurs="1" >
				<annotation>
					<documentation>The Name element defines the name of an AppVet tool service. For example, <Name>My Android Tester</Name>.</documentation>
				</annotation></element>
			<element name="Id" maxOccurs="1" minOccurs="1">
                <annotation>
                	<documentation>The Id element defines the ID of the AppVet tool service. The Id element must be alphabetic lowercase. For example, <Id>myandroidtester</Id>.</documentation>
                </annotation>
                <simpleType>
					<restriction base="string">
						<pattern value="[a-z]+" />
					</restriction>
				</simpleType>
			</element>
			<element name="VendorName" type="string" maxOccurs="1"
				minOccurs="0" >
				<annotation>
					<documentation>The VendorName element defines the vendor name of the AppVet tool service. For example, <Vendor>Example, Inc.</Vendor>.</documentation>
				</annotation></element>
			<element name="VendorWebsite" type="anyURI" maxOccurs="1"
				minOccurs="0" >
				<annotation>
					<documentation>The VendorWebsite element defines the vendor's website. For example, <VendorWebsite>https://www.example.com</VendorWebsite>.</documentation>
				</annotation></element>
			<element name="ReportFile" type="appvet:ReportFileType"
				maxOccurs="1" minOccurs="1">
				<annotation>
					<documentation>The ReportFile element defines the file type of the tool service report. The ReportFormat element must be TXT, PDF, HTML, or RTF. For example, <ReportFile>TXT</ReportFile>.</documentation>
				</annotation></element>
		</sequence>
	</complexType>

	<complexType name="ProtocolType">
		<annotation>
			<documentation>This type defines a remote AppVet-compatible tool
				service
				as synchronous or asynchronous.
			</documentation>
		</annotation>
		<sequence>
			<element name="Type" type="appvet:ProtocolNameType"
				maxOccurs="1" minOccurs="1">
                <annotation>
                	<documentation>The Type element defines the service protocol for the AppVet tool service. The Type element value must be SYNCHRONOUS, ASYNCHRONOUS, PUSH, or INTERNAL.</documentation>
                </annotation>
			</element>
			<choice>
				<element name="Synchronous" type="appvet:SynchronousType" >
					<annotation>
						<documentation>The Synchronous element defines the properties of an AppVet synchronous tool service.</documentation>
					</annotation></element>
				<element name="Asynchronous" type="appvet:AsynchronousType" >
					<annotation>
						<documentation>The Asynchronous element defines the properties of an AppVet asynchronous tool service.</documentation>
					</annotation></element>
				<element name="Push" type="appvet:PushType" >
					<annotation>
						<documentation>The Push element defines the properties of an AppVet push tool service.</documentation>
					</annotation></element>
				<element name="Internal" type="appvet:InternalType" >
					<annotation>
						<documentation>The Internal element defines the properties of an AppVet internal tool.</documentation>
					</annotation></element>
			</choice>
		</sequence>
	</complexType>

	<simpleType name="ReportFileType">
		<restriction base="string">
			<enumeration value="TXT" />
			<enumeration value="HTML" />
			<enumeration value="PDF" />
			<enumeration value="RTF" />
		</restriction>
	</simpleType>

	<complexType name="SynchronousType">
		<annotation>
			<documentation></documentation>
		</annotation>
		<sequence>
			<element name="Request" type="appvet:HTTPRequestType"
				minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>The Request element defines an HTML Form to be sent to an AppVet tool service via an HTTP Request message.</documentation>
				</annotation>
			</element>
			<element name="Response" type="appvet:HTTPResponseType"
				maxOccurs="1" minOccurs="1" >
				<annotation>
					<documentation>The Response element defines properties for the response from an AppVet synchronous tool service.</documentation>
				</annotation></element>
		</sequence>
	</complexType>

	<complexType name="AsynchronousType">
		<annotation>
			<documentation></documentation>
		</annotation>
		<sequence>
			<element name="Request" type="appvet:HTTPRequestType"
				minOccurs="1">
				<annotation>
					<documentation>
						The Request element defines an HTML Form to be
						sent to an AppVet tool service via an HTTP
						Request message.
					</documentation>
				</annotation>
			</element>
			<element name="Receipt" type="appvet:HTTPResponseType" maxOccurs="1" minOccurs="1"></element>
			<element name="PushResponse" type="appvet:HTTPRequestType"
				maxOccurs="1" minOccurs="1">
				<annotation>
					<documentation>
						The Reponse element defines the payload of an
						AppVet tool service response.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="PushType">
		<sequence>
		</sequence>
	</complexType>

	<complexType name="InternalType">
		<sequence>
		</sequence>
	</complexType>

	<complexType name="HTTPRequestType">
		<annotation>
			<documentation>The HTTP Request is used by AppVet to send an app to a tool service or 
by an asynchronous tool service to send a report to AppVet.

For APPVET->TOOL SERVICE

file: The app file to send to the tool service.
username: The user ID of the tool service account (optional)
password: The password for the tool service account (optional)
appid: The AppVet ID of the app (for asynchronous tools only)


For ASYNCHRONOUS SERVICE->APPVET

command: The AppVet command to submit reports (use 'SUBMIT_REPORT')
appid: The AppVet ID of the associated app
username: The AppVet user ID
password: The AppVet password
file: The report file
toolrisk: The risk assessment generated by the tool (i.e., 'PASS', 'WARNING', 'FAIL', 'ERROR')
</documentation>
		</annotation>
		<sequence>
			<element name="URL" type="anyURI" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>The URL element defines the URL of the AppVet tool service.
					</documentation>
				</annotation>
			</element>
			<element name="Method" type="appvet:MethodType" maxOccurs="1"
				minOccurs="1" >
				<annotation>
					<documentation>The Method element defines the HTTP action to be invoked (i.e., 'GET' or 'POST').</documentation>
				</annotation></element>
			<element name="Parameter" type="appvet:ParameterType"
				minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>The FormParameter element defines the HTML form parameters to be sent to the tool service. 
For asynchronous tool services, the form parameters must include the parameter "appid" to 
allow the reports to be matched by AppVet to their associated app. For services that require
login, the service must use 'userid' and 'password' parameters.


</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<complexType name="AsynchronousResponseType">
		<sequence>
			<element name="ReportPayload" type="boolean" default="false"
				maxOccurs="1" minOccurs="1" >
				<annotation>
					<documentation>The ReportPayload element defines whether a report is contained in the response from an AppVet asynchronous service. The value of ReportPayload for asynchronous services must always be false.</documentation>
				</annotation></element>
		</sequence>
	</complexType>

	<complexType name="ParameterType">
		<sequence>
			<element name="Name" type="string">
                <annotation>
                	<documentation>The Name element defines the name of the parameter. </documentation>
                </annotation>
			</element>
			<element name="Value" type="string" default="DEFINED_AT_RUNTIME">
				<annotation>
					<documentation>The Value element defines the value of the parameter element.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>

	<simpleType name="MethodType">
		<restriction base="string">
			<enumeration value="POST" />
			<enumeration value="GET" />
		</restriction>
	</simpleType>

	<simpleType name="ProtocolNameType">
		<restriction base="string">
			<enumeration value="SYNCHRONOUS" />
			<enumeration value="ASYNCHRONOUS" />
			<enumeration value="PUSH" />
			<enumeration value="INTERNAL" />
		</restriction>
	</simpleType>

	<complexType name="HTTPResponseType">
        <annotation>
        	<documentation>The HTTP Response type contains up to three elements: AppVetRiskHeaderName, ReportPayload, and StatusCode. 

For SYNCHRONOUS SERVICES

For synchronous services, the HTTP response should contain a payload consisting of the tool report (or null) and
have the HTTP header parameter 'toolrisk' that defines the assessed risk (i.e., 'PASS', 'WARNING', 'FAIL', or 'ERROR'). 
In addition, HTTP code '200' indicating OK or '400' indicating Bad Request must be used.

For ASYNCHRONOUS SERVICES

For asynchronous services, the HTTP response is used to indicate correct receipt of an app by the tool and is
therefore empty but with an HTTP code of '202' incidating correct receipt of the app or '400' bad request.</documentation>
        </annotation>
        <sequence>
			<element name="AppVetRiskHeaderName" type="string"
				default="APPVET_TOOL_RESULT" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>The AppVetRiskHeaderName element defines the
HTTP Response Header name for a synchronous tool
service's risk assessment category (ERROR, FAIL, WARNING, 
or PASS). For synchronous services, the 
AppVetResultHeaderName value should be 
set to "toolrisk". For all service types, the AppVetRiskHeaderName
element should not be set.
					</documentation>
				</annotation>
			</element>
			<element name="ReportPayload" type="boolean" default="true"
				maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						The ReportPayload element defines whether the
						response message contains a report file (in
						string form). If no report
					</documentation>
				</annotation>
			</element>
			<element name="StatusCode" type="string" maxOccurs="unbounded" minOccurs="0">
				<annotation>
					<documentation>This is the HTTP status code returned by the tool service. </documentation>
				</annotation></element>
		</sequence>
	</complexType>


</schema>

=== joeyramone76/appvet/appvet_installer_files/deploy/conf/tool_adapters/registration.xml
<?xml version="1.0" encoding="UTF-8"?>
<appvet:ToolServiceAdapter xmlns:appvet="http://csrc.nist.gov/groups/SNS/appvet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/groups/SNS/appvet ToolServiceAdapter.xsd ">
  <appvet:Description>
    <appvet:Name>Registration</appvet:Name>
    <appvet:Id>registration</appvet:Id>
    <appvet:ReportFile>HTML</appvet:ReportFile>
  </appvet:Description>
  <appvet:Protocol>
    <appvet:Type>INTERNAL</appvet:Type>
    <appvet:Internal/>
  </appvet:Protocol>
</appvet:ToolServiceAdapter>

=== joeyramone76/appvet/appvet_installer_files/deploy/conf/unused_tool_adapters/androwarn.xml
<?xml version="1.0" encoding="UTF-8"?>
<appvet:ToolServiceAdapter xmlns:appvet="http://csrc.nist.gov/projects/appvet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/groups/SNS/appvet ToolServiceAdapter.xsd ">
  <appvet:Description>
    <appvet:Name>Androwarn</appvet:Name>
    <appvet:Id>androwarn</appvet:Id>
    <appvet:VendorName>Maaaaz</appvet:VendorName>
    <appvet:ReportFile>TXT</appvet:ReportFile>
  </appvet:Description>
  <appvet:Protocol>
    <appvet:Type>SYNCHRONOUS</appvet:Type>
    <appvet:Synchronous>
      <appvet:Request>
        <appvet:URL>http://gmuanalyzer.nist.gov/atptoolwrapper/SynchronousService</appvet:URL>
        <appvet:Method>POST</appvet:Method>
        <appvet:Parameter>
          <appvet:Name>file</appvet:Name>
          <appvet:Value>APP_FILE</appvet:Value>
        </appvet:Parameter>
      </appvet:Request>
      <appvet:Response>
        <appvet:AppVetRiskHeaderName>toolrisk
        </appvet:AppVetRiskHeaderName>
        <appvet:ReportPayload>true</appvet:ReportPayload>
      </appvet:Response>
    </appvet:Synchronous>
  </appvet:Protocol>
</appvet:ToolServiceAdapter>

=== joeyramone76/appvet/appvet_installer_files/deploy/conf/tool_adapters/android/registration.xml
<?xml version="1.0" encoding="UTF-8"?>
<appvet:ToolServiceAdapter xmlns:appvet="http://csrc.nist.gov/projects/appvet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/projects/appvet ToolServiceAdapter.xsd ">
  <appvet:Description>
    <appvet:Name>Registration</appvet:Name>
    <appvet:Id>registration</appvet:Id>
        <appvet:VendorName>NIST</appvet:VendorName>
    <appvet:VendorWebsite>http://csrc.nist.gov/projects/appvet</appvet:VendorWebsite>
    <appvet:ReportFile>HTML</appvet:ReportFile>
  </appvet:Description>
  <appvet:Protocol>
    <appvet:Type>INTERNAL</appvet:Type>
    <appvet:Internal/>
  </appvet:Protocol>
</appvet:ToolServiceAdapter>

=== joeyramone76/appvet/appvet_installer_files/deploy/conf/tool_adapters/android/masterkeyextrafield.xml
<?xml version="1.0" encoding="UTF-8"?>

<appvet:ToolServiceAdapter xmlns:appvet="http://csrc.nist.gov/projects/appvet"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://csrc.nist.gov/projects/appvet ToolServiceAdapter.xsd ">

	<appvet:Description>
		<appvet:Name>MasterKey ExtraField Test</appvet:Name>
		<appvet:Id>masterkeyextrafield</appvet:Id>
		<appvet:VendorName>NIST</appvet:VendorName>
    <appvet:VendorWebsite>https://appsec.nist.gov/android-masterkey-extrafield-test</appvet:VendorWebsite>

		<appvet:ReportFile>HTML</appvet:ReportFile>
	</appvet:Description>

	<appvet:Protocol>
		<appvet:Type>ASYNCHRONOUS</appvet:Type>
		<appvet:Asynchronous>
			<appvet:Request>
				<appvet:URL>http://129.6.52.146/android-masterkey-extrafield-test/AsynchronousService
				</appvet:URL>
				<appvet:Method>POST</appvet:Method>


				<appvet:Parameter>
					<appvet:Name>appid</appvet:Name>
					<appvet:Value>APPVET_DEFINED</appvet:Value>
				</appvet:Parameter>

				<appvet:Parameter>
					<appvet:Name>file</appvet:Name>
					<appvet:Value>APP_FILE</appvet:Value>
				</appvet:Parameter>

			</appvet:Request>

			<appvet:Response />


		


		</appvet:Asynchronous>

	</appvet:Protocol>

</appvet:ToolServiceAdapter>
